### ISSUE TITLE
Memory management for test file?

### ISSUE THREAD

**Issue by njhofmann** [austenke/a1-part2#8]
You guys appear to be missing quite a few delete statements for your queues and the objects you push in. 

So for the sake of memory management in the test file, and to help clarify whether or not a queue should delete objects it has been given when it itself is deleted, could you add some delete statements at the end of each test method? 

I think making a Queue NOT delete Objects it has been given is the superior design choice because I can imagine some memory issues when passing the same object to multiple Queues, then deleting one of the Queues and thus the Object as well (I think?).

**Comment by austenke** [comment]
PR accepted.
